export  const GET_PROJECT_TASKS = 'GET_PROJECT_TASKS';
export const GET_ERRORS = 'GET_ERRORS';
export const DELETE_PROJECT_TASK = 'DELETE_PROJECT_TASK';
export const GET_PROJECT_TASK = 'GET_PROJECT_TASK';
export const GET_PROJECT_ERROR = 'GET_PROJECT_ERROR';
export const GET_PROJECTS = 'GET_PROJECTS';
export const DELETE_PROJECT = 'DELETE_PROJECT';